version: '3'
services:
  mongo:
    image: 'mongo:latest'
    volumes:
      - './data/db:/data/db'
    ports:
      - 27017:27017
  parse:
    image: 'parseplatform/parse-server:latest'
    environment:
      - PARSE_SERVER_APPLICATION_ID=parse
      - PARSE_SERVER_MASTER_KEY=parse@master123!
      - PARSE_SERVER_DATABASE_URI=mongodb://mongo:27017/parse
      - PARSE_SERVER_MOUNT_PATH=/parse
    ports:
      - '1337:1337'
    links:
      - mongo
  parse-dashboard:
    image: 'parseplatform/parse-dashboard'
    ports:
      - '4040:4040'
    environment:
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=true
      - PARSE_DASHBOARD_SERVER_URL=/api
      - PARSE_DASHBOARD_MASTER_KEY=parse@master123!
      - PARSE_DASHBOARD_APP_ID=parse
      - PARSE_DASHBOARD_APP_NAME=MyParseApp
      - PARSE_DASHBOARD_USER_ID=admin
      - PARSE_DASHBOARD_USER_PASSWORD=pwd@admin123!
      - MOUNT_PATH=/dashboard/
    links:
      - parse
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx:/etc/nginx/sites-enabled'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
      # letsencrypt will put generated pems under /etc/letsencrypt/live/yourdomain.com, copy them to nginx container. 
      # - '/etc/letsencrypt/live/yourdomain.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem'
      # - '/etc/letsencrypt/live/yourdomain.com/privkey.pem:/etc/nginx/ssl/privkey.pem'
    links:
      - parse-dashboard
      - parse
      - portainer
volumes:
  portainer_data: